/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import connection.ClinicDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ChiSoDinhDuong;
import model.Patient;
import model.Relatives;

/**
 *
 * @author Admin
 */
public class FrameXemChiSoDinhDuong extends javax.swing.JFrame {

    /**
     * Creates new form FrameXemChiSoDinhDuong
     */
     private DefaultTableModel tblModel;
    public FrameXemChiSoDinhDuong() {
        initComponents();
        setLocationRelativeTo(null);
        ArrayList<Patient> listPatient = new ClinicDAO().getAllPatient();
        ArrayList<ChiSoDinhDuong> listCSDD = new ClinicDAO().getAllChiSoDinhDuong();
        setTableData(listPatient, listCSDD);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCSDD = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonSuaCSDD = new javax.swing.JButton();
        jButtonShowAll = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSearch = new javax.swing.JTextField();
        jbuttonSearch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setResizable(false);
        getContentPane().setLayout(null);

        jTableCSDD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên", "C. Cao tối thiểu", "C. Cao", "C. Cao tối đa", "C. Nặng tối thiểu", "C. Nặng", "C. Nặng tối đa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableCSDD);
        if (jTableCSDD.getColumnModel().getColumnCount() > 0) {
            jTableCSDD.getColumnModel().getColumn(0).setResizable(false);
            jTableCSDD.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTableCSDD.getColumnModel().getColumn(1).setResizable(false);
            jTableCSDD.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTableCSDD.getColumnModel().getColumn(2).setResizable(false);
            jTableCSDD.getColumnModel().getColumn(3).setResizable(false);
            jTableCSDD.getColumnModel().getColumn(4).setResizable(false);
            jTableCSDD.getColumnModel().getColumn(5).setResizable(false);
            jTableCSDD.getColumnModel().getColumn(6).setResizable(false);
            jTableCSDD.getColumnModel().getColumn(7).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 120, 1000, 530);

        jButton2.setBackground(new java.awt.Color(0, 153, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("ĐƯA RA CẢNH BÁO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(580, 690, 191, 40);

        jButton3.setBackground(new java.awt.Color(0, 153, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("QUAY LẠI");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(100, 690, 150, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("CHỈ SỐ DINH DƯỠNG");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 20, 270, 29);

        jButtonSuaCSDD.setBackground(new java.awt.Color(0, 153, 102));
        jButtonSuaCSDD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonSuaCSDD.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSuaCSDD.setText("SỬA CHỈ SỐ DINH DƯỠNG");
        jButtonSuaCSDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaCSDDActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSuaCSDD);
        jButtonSuaCSDD.setBounds(290, 690, 249, 40);

        jButtonShowAll.setBackground(new java.awt.Color(0, 153, 102));
        jButtonShowAll.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonShowAll.setForeground(new java.awt.Color(255, 255, 255));
        jButtonShowAll.setText("HIỆN TẤT CẢ ");
        jButtonShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowAllActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonShowAll);
        jButtonShowAll.setBounds(790, 690, 170, 39);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nhập họ tên bệnh nhân: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 70, 150, 20);
        getContentPane().add(jTextFieldSearch);
        jTextFieldSearch.setBounds(300, 60, 360, 30);

        jbuttonSearch.setBackground(new java.awt.Color(0, 153, 102));
        jbuttonSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbuttonSearch.setForeground(new java.awt.Color(255, 255, 255));
        jbuttonSearch.setText("TÌM KIẾM");
        jbuttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonSearchActionPerformed(evt);
            }
        });
        getContentPane().add(jbuttonSearch);
        jbuttonSearch.setBounds(700, 60, 130, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/48360123_1946174842344109_3833490493317054464_n.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1000, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            new FrameXemThongTin().setVisible(true);
    this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int row = jTableCSDD.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn bệnh nhân trước"
                    + "", "Lỗi: ", JOptionPane.ERROR_MESSAGE);
        } else {
            new FrameGuiCanhBao().setVisible(true);
            this.dispose();
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonSuaCSDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaCSDDActionPerformed
        int row = jTableCSDD.getSelectedRow();
        if(row==-1){
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn bệnh nhân trước"
                    + "", "Lỗi: ", JOptionPane.ERROR_MESSAGE);   
        }
        else{
        int CSDDID = Integer.valueOf(String.valueOf(jTableCSDD.getValueAt(row, 0)));
         ArrayList<ChiSoDinhDuong> listCSDD = new ClinicDAO().getAllChiSoDinhDuong();
         
                
        int idEdit = listCSDD.get(row).getIDPatient();
        new FrameSuaTTChiSoDinhDuong(idEdit).setVisible(true);
        this.dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSuaCSDDActionPerformed

    private void jButtonShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowAllActionPerformed
        tblModel.setRowCount(0);
        setTableData(new ClinicDAO().getAllPatient(), new ClinicDAO().getAllChiSoDinhDuong());
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonShowAllActionPerformed

    private void jbuttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonSearchActionPerformed
        ArrayList<Patient> list = new ArrayList<>();
        String name  = jTextFieldSearch.getText().trim();
        list = new ClinicDAO().getPatientByName(name);
        ArrayList<ChiSoDinhDuong> listCSDD = new ArrayList<>();
        ArrayList<Patient> listChildren = new ArrayList<>();
        for (Patient patient : list) {
            if (patient.getKindOfPatient().equals("Trẻ em")) {
                listChildren.add(patient);
            }
        }
        for (int i = 0; i < listChildren.size(); i++) {
            listCSDD.add(new ClinicDAO().getChiSoDinhDuongByID(listChildren.get(i).getID()));
        }
        if (listChildren.size()<1) {
            JOptionPane.showMessageDialog(rootPane, "Không có bệnh nhân thỏa mãn!");
        }
        else{
            tblModel = (DefaultTableModel) jTableCSDD.getModel();
            tblModel.setRowCount(0);
            for(int i = 0;i< listCSDD.size();  i++) {
                    tblModel.addRow(new Object[]{listCSDD.get(i).getIDPatient(), listChildren.get(i).getName(),
                        listCSDD.get(i).getMinHeight(),listCSDD.get(i).getHeight(),
                        listCSDD.get(i).getMaxHeight(),
                        listCSDD.get(i).getMinWeight(),
                        listCSDD.get(i).getWeight(),
                        listCSDD.get(i).getMaxWeight()
                        

                    });
                }
            
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jbuttonSearchActionPerformed

    /**
     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrameXemChiSoDinhDuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrameXemChiSoDinhDuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrameXemChiSoDinhDuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrameXemChiSoDinhDuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrameXemChiSoDinhDuong().setVisible(true);
//            }
//        });
//    }
private void setTableData(ArrayList<Patient> listPatient, ArrayList<ChiSoDinhDuong> listCSDD){
    ArrayList<Patient> listPatientByCSDD = new ArrayList<>();
        for (int i = 0; i < listCSDD.size(); i++) {
            for (int j = 0; j < listPatient.size(); j++) {
                if(listPatient.get(j).getID()==listCSDD.get(i).getIDPatient()){
                    listPatientByCSDD.add(listPatient.get(j));
                }
                
            }
        }
        
        tblModel = (DefaultTableModel) jTableCSDD.getModel();
        for(int i = 0;i< listCSDD.size();  i++) {
                    tblModel.addRow(new Object[]{listCSDD.get(i).getIDPatient(), listPatientByCSDD.get(i).getName(),
                        listCSDD.get(i).getMinHeight(),listCSDD.get(i).getHeight(),
                        listCSDD.get(i).getMaxHeight(),
                        listCSDD.get(i).getMinWeight(),
                        listCSDD.get(i).getWeight(),
                        listCSDD.get(i).getMaxWeight()
                        

                    });
                }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonShowAll;
    private javax.swing.JButton jButtonSuaCSDD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCSDD;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JButton jbuttonSearch;
    // End of variables declaration//GEN-END:variables
}
