/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import connection.ClinicDAO;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Patient;

/**
 *
 * @author Admin
 */
public class FrameTaoSuKien extends javax.swing.JFrame {

    /**
     * Creates new form FrameTaoSuKien
     */
    private DefaultTableModel tblModel;
    public FrameTaoSuKien() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldAgeMin = new javax.swing.JTextField();
        jTextFieldAgeMax = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePatient = new javax.swing.JTable();
        jButtonTao = new javax.swing.JButton();
        jButtonQuayLai = new javax.swing.JButton();
        jButtonSearch = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("TẠO SỰ KIỆN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(360, 10, 240, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nhập độ tuổi các bà mẹ muốn tạo sự kiện");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 70, 257, 17);
        getContentPane().add(jTextFieldAgeMin);
        jTextFieldAgeMin.setBounds(280, 60, 50, 30);
        getContentPane().add(jTextFieldAgeMax);
        jTextFieldAgeMax.setBounds(360, 60, 48, 30);

        jLabel3.setText("-");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 70, 20, 14);

        jTablePatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên", "Ngày Sinh", "Địa Chỉ", "Số Điện Thoại", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePatient);
        if (jTablePatient.getColumnModel().getColumnCount() > 0) {
            jTablePatient.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 150, 1000, 520);

        jButtonTao.setBackground(new java.awt.Color(0, 153, 102));
        jButtonTao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonTao.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTao.setText("Tạo");
        jButtonTao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTaoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTao);
        jButtonTao.setBounds(860, 700, 110, 40);

        jButtonQuayLai.setBackground(new java.awt.Color(0, 153, 102));
        jButtonQuayLai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonQuayLai.setForeground(new java.awt.Color(255, 255, 255));
        jButtonQuayLai.setText("Quay lại");
        jButtonQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuayLaiActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonQuayLai);
        jButtonQuayLai.setBounds(680, 700, 110, 40);

        jButtonSearch.setBackground(new java.awt.Color(0, 153, 102));
        jButtonSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonSearch.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSearch.setText("Tìm kiếm");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSearch);
        jButtonSearch.setBounds(450, 60, 87, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Nhập tên sự kiện");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 110, 130, 17);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(130, 100, 350, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/48360123_1946174842344109_3833490493317054464_n.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1000, 800);

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 34, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuayLaiActionPerformed
        new FrameXemThongTinThaiKi().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonQuayLaiActionPerformed

    private void jButtonTaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTaoActionPerformed
        int cofirm = JOptionPane.showConfirmDialog(rootPane, ""
                    + "Gửi email đến các bà mẹ trong danh sách?");
            if (cofirm==JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(rootPane, "Gửi thành công!");
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTaoActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
         ArrayList<Patient> listPatient = new ArrayList<>();
        try {
            int ageMin = Integer.parseInt(jTextFieldAgeMin.getText());
            int ageMax = Integer.parseInt(jTextFieldAgeMax.getText());
            if (ageMax>100||ageMax<0||ageMin>100||ageMin<0) {
                 JOptionPane.showMessageDialog(rootPane, "Độ tuổi không hợp lệ!");
            }
            else listPatient = new ClinicDAO().MakeEvent(Integer.parseInt(jTextFieldAgeMin.getText()), Integer.parseInt(jTextFieldAgeMax.getText()) );
            if (listPatient==null) {
                 JOptionPane.showMessageDialog(rootPane, "Không có bện nhân nào trong độ tuổi!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập số vào ô độ tuổi"
                    + "", "Lỗi: ", JOptionPane.ERROR_MESSAGE);  
        }
       
        tblModel = (DefaultTableModel) jTablePatient.getModel();
        tblModel.setRowCount(0);
        for (Patient patient : listPatient) {
                    tblModel.addRow(new Object[]{patient.getID(), patient.getName(), patient.getDateOfBirth(),
                        patient.getAddress(), patient.getPhoneNumer(), patient.getEmail()
                    });
                } 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSearchActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrameTaoSuKien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrameTaoSuKien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrameTaoSuKien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrameTaoSuKien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrameTaoSuKien().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonQuayLai;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonTao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePatient;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldAgeMax;
    private javax.swing.JTextField jTextFieldAgeMin;
    // End of variables declaration//GEN-END:variables
}
