/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import connection.ClinicDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Patient;
import model.Relatives;

/**
 *
 * @author Admin
 */
public class FrameSuaTTBenhNhan extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form FrameSuaTTBenhNhan
     */
    public FrameSuaTTBenhNhan(int patientID ) {
        initComponents();
        setLocationRelativeTo(null);
        Patient p = new ClinicDAO().getPatientByID(patientID);
        Relatives r = new ClinicDAO().getRelativeByID(patientID);
        jTextFieldID.setText("" + p.getID());
        jTextFieldHoTen.setText(p.getName());
        jTextFieldNgaySinh.setText(new SimpleDateFormat("dd/MM/yyyy").format(p.getDateOfBirth()));
        jTextFieldDiaChi.setText(p.getAddress());
        jTextFieldSDT.setText(p.getPhoneNumer());
        jTextFieldEmail.setText(p.getEmail());
        //System.out.println(""+p.getSex());
        if (p.getSex().equals("Nam")) { // nếu giới tính bệnh nhân là nam thì nút Nam được chọn 
            //System.out.println(""+p.getSex());
            jRadioButtonNam.setSelected(true);
        } else {
            jRadioButtonNu.setSelected(true);
        }
        if (p.getKindOfPatient().equals("Mẹ mang thai")) {
            jRadioButtonMeMangThai.setSelected(true);
        } else {
            jRadioButtonTre.setSelected(true);
        }
        jTextFieldIDNt.setText(String.valueOf(r.getID()));
        jTextFieldHoTenNt.setText(r.getName());
        jTextFieldDiaChiNt.setText(r.getAddress());
        jTextFieldSDTNt.setText(r.getPhoneNumber());
        jTextFieldQuanHe.setText(r.getRelation());
        
        jButtonLamMoi.addActionListener(this);
        jButtonSuaBN.addActionListener(this);
        jButtonQuayLai.addActionListener(this);
        labelErrorHoTen.setText("");
        labelErrorSDT.setText("");
        labelErrorEmail.setText("");
        labelErrorHotenNt.setText("");
        labelErrorSDTNt.setText("");
        labelErrorQuanHe.setText("");
        labelErrorNgaySinh.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButtonQuayLai = new javax.swing.JButton();
        JLabelID = new javax.swing.JLabel();
        jLabelIDNguoiThan = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonSuaBN = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButtonLamMoi = new javax.swing.JButton();
        jTextFieldID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIDNt = new javax.swing.JTextField();
        jLabelHoTen = new javax.swing.JLabel();
        jLabelNgaySinh = new javax.swing.JLabel();
        jLabelGioiTinh = new javax.swing.JLabel();
        jLabelSDT = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelDiaChi = new javax.swing.JLabel();
        jTextFieldHoTen = new javax.swing.JTextField();
        jTextFieldNgaySinh = new javax.swing.JTextField();
        jTextFieldSDT = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldDiaChi = new javax.swing.JTextField();
        jLabelHoTenNguoiThan = new javax.swing.JLabel();
        jLabelSDTNguoiThan = new javax.swing.JLabel();
        jLabelDiaChiNguoiThan = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jRadioButtonNam = new javax.swing.JRadioButton();
        jRadioButtonNu = new javax.swing.JRadioButton();
        jTextFieldHoTenNt = new javax.swing.JTextField();
        jTextFieldSDTNt = new javax.swing.JTextField();
        jTextFieldDiaChiNt = new javax.swing.JTextField();
        jTextFieldQuanHe = new javax.swing.JTextField();
        jLabelLoaiBenhNhan = new javax.swing.JLabel();
        jRadioButtonMeMangThai = new javax.swing.JRadioButton();
        jRadioButtonTre = new javax.swing.JRadioButton();
        labelErrorHoTen = new javax.swing.JLabel();
        labelErrorNgaySinh = new javax.swing.JLabel();
        labelErrorSDT = new javax.swing.JLabel();
        labelErrorEmail = new javax.swing.JLabel();
        labelErrorQuanHe = new javax.swing.JLabel();
        labelErrorHotenNt = new javax.swing.JLabel();
        labelErrorSDTNt = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setResizable(false);
        getContentPane().setLayout(null);

        jButtonQuayLai.setBackground(new java.awt.Color(0, 153, 102));
        jButtonQuayLai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonQuayLai.setForeground(new java.awt.Color(255, 255, 255));
        jButtonQuayLai.setText("QUAY LẠI");
        jButtonQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuayLaiActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonQuayLai);
        jButtonQuayLai.setBounds(500, 710, 125, 40);

        JLabelID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JLabelID.setText("ID");
        getContentPane().add(JLabelID);
        JLabelID.setBounds(46, 119, 14, 17);

        jLabelIDNguoiThan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelIDNguoiThan.setText("ID");
        getContentPane().add(jLabelIDNguoiThan);
        jLabelIDNguoiThan.setBounds(530, 120, 14, 17);

        jLabel19.setEnabled(false);
        getContentPane().add(jLabel19);
        jLabel19.setBounds(929, 65, 0, 0);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("NGƯỜI THÂN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(723, 54, 200, 22);

        jButtonSuaBN.setBackground(new java.awt.Color(0, 153, 102));
        jButtonSuaBN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonSuaBN.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSuaBN.setText("SỬA");
        getContentPane().add(jButtonSuaBN);
        jButtonSuaBN.setBounds(680, 710, 90, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("BỆNH NHÂN");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(103, 53, 142, 25);

        jButtonLamMoi.setBackground(new java.awt.Color(0, 153, 102));
        jButtonLamMoi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLamMoi.setText("LÀM  MỚI");
        getContentPane().add(jButtonLamMoi);
        jButtonLamMoi.setBounds(820, 710, 130, 40);

        jTextFieldID.setEnabled(false);
        getContentPane().add(jTextFieldID);
        jTextFieldID.setBounds(170, 120, 200, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("SỬA THÔNG TIN BỆNH NHÂN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 10, 370, 27);

        jTextFieldIDNt.setEnabled(false);
        getContentPane().add(jTextFieldIDNt);
        jTextFieldIDNt.setBounds(730, 110, 180, 30);

        jLabelHoTen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelHoTen.setText("HỌ TÊN");
        getContentPane().add(jLabelHoTen);
        jLabelHoTen.setBounds(40, 190, 70, 17);

        jLabelNgaySinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNgaySinh.setText("NGÀY SINH");
        getContentPane().add(jLabelNgaySinh);
        jLabelNgaySinh.setBounds(40, 260, 90, 17);

        jLabelGioiTinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelGioiTinh.setText("GIỚI TÍNH");
        getContentPane().add(jLabelGioiTinh);
        jLabelGioiTinh.setBounds(40, 330, 80, 17);

        jLabelSDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSDT.setText("SỐ ĐIỆN THOẠI");
        getContentPane().add(jLabelSDT);
        jLabelSDT.setBounds(40, 400, 110, 17);

        jLabelEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelEmail.setText("EMAIL");
        getContentPane().add(jLabelEmail);
        jLabelEmail.setBounds(50, 470, 60, 17);

        jLabelDiaChi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDiaChi.setText("ĐỊA CHỈ");
        getContentPane().add(jLabelDiaChi);
        jLabelDiaChi.setBounds(50, 630, 70, 17);
        getContentPane().add(jTextFieldHoTen);
        jTextFieldHoTen.setBounds(170, 180, 200, 30);
        getContentPane().add(jTextFieldNgaySinh);
        jTextFieldNgaySinh.setBounds(170, 250, 200, 30);
        getContentPane().add(jTextFieldSDT);
        jTextFieldSDT.setBounds(170, 390, 200, 30);
        getContentPane().add(jTextFieldEmail);
        jTextFieldEmail.setBounds(170, 460, 200, 30);
        getContentPane().add(jTextFieldDiaChi);
        jTextFieldDiaChi.setBounds(170, 620, 200, 30);

        jLabelHoTenNguoiThan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelHoTenNguoiThan.setText("HỌ TÊN");
        getContentPane().add(jLabelHoTenNguoiThan);
        jLabelHoTenNguoiThan.setBounds(530, 190, 48, 17);

        jLabelSDTNguoiThan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSDTNguoiThan.setText("SỐ ĐIỆN THOẠI");
        getContentPane().add(jLabelSDTNguoiThan);
        jLabelSDTNguoiThan.setBounds(530, 260, 96, 17);

        jLabelDiaChiNguoiThan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDiaChiNguoiThan.setText("ĐỊA CHỈ");
        getContentPane().add(jLabelDiaChiNguoiThan);
        jLabelDiaChiNguoiThan.setBounds(530, 330, 48, 17);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("QUAN HỆ VỚI BỆNH NHÂN");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(530, 400, 160, 17);

        buttonGroup1.add(jRadioButtonNam);
        jRadioButtonNam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonNam.setText("Nam");
        getContentPane().add(jRadioButtonNam);
        jRadioButtonNam.setBounds(170, 320, 60, 25);

        buttonGroup1.add(jRadioButtonNu);
        jRadioButtonNu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonNu.setText("Nữ");
        getContentPane().add(jRadioButtonNu);
        jRadioButtonNu.setBounds(260, 320, 43, 25);
        getContentPane().add(jTextFieldHoTenNt);
        jTextFieldHoTenNt.setBounds(730, 180, 180, 30);
        getContentPane().add(jTextFieldSDTNt);
        jTextFieldSDTNt.setBounds(730, 250, 180, 30);
        getContentPane().add(jTextFieldDiaChiNt);
        jTextFieldDiaChiNt.setBounds(730, 320, 180, 30);
        getContentPane().add(jTextFieldQuanHe);
        jTextFieldQuanHe.setBounds(730, 390, 180, 30);

        jLabelLoaiBenhNhan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelLoaiBenhNhan.setText("LOẠI BỆNH NHÂN");
        getContentPane().add(jLabelLoaiBenhNhan);
        jLabelLoaiBenhNhan.setBounds(40, 550, 120, 17);

        buttonGroup2.add(jRadioButtonMeMangThai);
        jRadioButtonMeMangThai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonMeMangThai.setText("MẸ MANG THAI");
        getContentPane().add(jRadioButtonMeMangThai);
        jRadioButtonMeMangThai.setBounds(170, 550, 120, 25);

        buttonGroup2.add(jRadioButtonTre);
        jRadioButtonTre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonTre.setText("TRẺ EM");
        getContentPane().add(jRadioButtonTre);
        jRadioButtonTre.setBounds(300, 550, 90, 25);

        labelErrorHoTen.setForeground(new java.awt.Color(255, 51, 51));
        labelErrorHoTen.setText("jLabel3");
        getContentPane().add(labelErrorHoTen);
        labelErrorHoTen.setBounds(170, 220, 200, 14);

        labelErrorNgaySinh.setForeground(new java.awt.Color(255, 51, 51));
        labelErrorNgaySinh.setText("jLabel3");
        getContentPane().add(labelErrorNgaySinh);
        labelErrorNgaySinh.setBounds(170, 290, 330, 14);

        labelErrorSDT.setForeground(new java.awt.Color(255, 51, 51));
        labelErrorSDT.setText("jLabel3");
        getContentPane().add(labelErrorSDT);
        labelErrorSDT.setBounds(170, 430, 200, 14);

        labelErrorEmail.setForeground(new java.awt.Color(255, 51, 51));
        labelErrorEmail.setText("jLabel3");
        getContentPane().add(labelErrorEmail);
        labelErrorEmail.setBounds(170, 500, 200, 14);

        labelErrorQuanHe.setForeground(new java.awt.Color(255, 51, 51));
        labelErrorQuanHe.setText("jLabel12");
        getContentPane().add(labelErrorQuanHe);
        labelErrorQuanHe.setBounds(730, 440, 250, 14);

        labelErrorHotenNt.setForeground(new java.awt.Color(255, 51, 51));
        labelErrorHotenNt.setText("jLabel12");
        getContentPane().add(labelErrorHotenNt);
        labelErrorHotenNt.setBounds(730, 220, 180, 20);

        labelErrorSDTNt.setForeground(new java.awt.Color(255, 51, 51));
        labelErrorSDTNt.setText("jLabel12");
        getContentPane().add(labelErrorSDTNt);
        labelErrorSDTNt.setBounds(730, 290, 180, 14);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/48360123_1946174842344109_3833490493317054464_n.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1000, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuayLaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonQuayLaiActionPerformed

    /**
     * @param args the command line arguments
     */
//     public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrameThemBenhNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrameThemBenhNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrameThemBenhNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrameThemBenhNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrameThemBenhNhan().setVisible(true);
//            }
//        });
//    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelID;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonLamMoi;
    private javax.swing.JButton jButtonQuayLai;
    private javax.swing.JButton jButtonSuaBN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDiaChi;
    private javax.swing.JLabel jLabelDiaChiNguoiThan;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelGioiTinh;
    private javax.swing.JLabel jLabelHoTen;
    private javax.swing.JLabel jLabelHoTenNguoiThan;
    private javax.swing.JLabel jLabelIDNguoiThan;
    private javax.swing.JLabel jLabelLoaiBenhNhan;
    private javax.swing.JLabel jLabelNgaySinh;
    private javax.swing.JLabel jLabelSDT;
    private javax.swing.JLabel jLabelSDTNguoiThan;
    private javax.swing.JRadioButton jRadioButtonMeMangThai;
    private javax.swing.JRadioButton jRadioButtonNam;
    private javax.swing.JRadioButton jRadioButtonNu;
    private javax.swing.JRadioButton jRadioButtonTre;
    private javax.swing.JTextField jTextFieldDiaChi;
    private javax.swing.JTextField jTextFieldDiaChiNt;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldHoTen;
    private javax.swing.JTextField jTextFieldHoTenNt;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldIDNt;
    private javax.swing.JTextField jTextFieldNgaySinh;
    private javax.swing.JTextField jTextFieldQuanHe;
    private javax.swing.JTextField jTextFieldSDT;
    private javax.swing.JTextField jTextFieldSDTNt;
    private javax.swing.JLabel labelErrorEmail;
    private javax.swing.JLabel labelErrorHoTen;
    private javax.swing.JLabel labelErrorHotenNt;
    private javax.swing.JLabel labelErrorNgaySinh;
    private javax.swing.JLabel labelErrorQuanHe;
    private javax.swing.JLabel labelErrorSDT;
    private javax.swing.JLabel labelErrorSDTNt;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource().equals(jButtonSuaBN)){
            btnEditClick();
        }
        else if(e.getSource().equals(jButtonQuayLai)){
            btnQuayLaiClick();
        }
        else {
            btnLamMoiClick();
        }
        
        
    }
     public void  btnEditClick(){
        Patient p = new Patient();
        Relatives r = new Relatives();
        labelErrorHoTen.setText("");
        labelErrorSDT.setText("");
        labelErrorEmail.setText("");
        labelErrorHotenNt.setText("");
        labelErrorSDTNt.setText("");
        labelErrorQuanHe.setText("");
        labelErrorNgaySinh.setText("");
        try{
            boolean test = true;
            p.setID(Integer.parseInt(jTextFieldID.getText()));
            if(jTextFieldHoTen.getText().equals("")){ // kiểm tra họ tên bệnh nhân có trống không
                labelErrorHoTen.setText("Chưa nhập tên bệnh nhân");
                test = false;
            }
            else{
                p.setName(jTextFieldHoTen.getText());
            }
            p.setAddress(jTextFieldDiaChi.getText());
            String patternDate = "[0-9]{2}/[0-9]{2}/[0-9]{4}"; // định dạng cua ngày sinh dd/MM/yyyy
                if (jTextFieldNgaySinh.getText().matches(patternDate)) { // kiểm tra xem nhày sinh nhập vào có đúng định dạng không
                    String date = jTextFieldNgaySinh.getText().substring(0, 2); // lấy ngày
                    String month = jTextFieldNgaySinh.getText().substring(3, 5); // lấy tháng
                    String year = jTextFieldNgaySinh.getText().substring(6, 10); // lấy năm
                    int dateNumber = Integer.parseInt(date); // chuyển ngày sang kiểu Int
                    int monthNumber = Integer.parseInt(month);
                    int yearNumber = Integer.parseInt(year);
                    if(monthNumber<0||monthNumber>12||dateNumber<0||dateNumber>31){ // nếu tháng > 12 hoặc <0 hoặc ngày < 0 hoặc ngày > 31 thì ngày sinh không hợp lệ
                        labelErrorNgaySinh.setText("Ngày tháng không hợp lệ");
                        test = false;
                    }
                    else{
                        if(monthNumber==4||monthNumber==6||monthNumber==9||monthNumber==11) // nếu là tháng có 30 ngày
                        {
                            if(dateNumber==31){ // ngày = 31 không hợp lệ
                                 labelErrorNgaySinh.setText("Ngày tháng không hợp lệ");
                                test = false;
                            }
                        }
                        if(monthNumber==2){ // nếu là tháng 2
                            if (!((yearNumber % 4 == 0 && yearNumber % 100 != 0) || (yearNumber % 400 == 0))){ // nếu không phải năm nhuận
                                if(dateNumber>=29){ // nếu xuất hiện ngày 29/2 trong năm không phải năm nhuận
                                 labelErrorNgaySinh.setText("Ngày tháng không hợp lệ");
                                test = false;
                                }
                            }
                            else{ // nếu là năm nhuận
                                if (dateNumber>29) { // tháng 2 có thể có ngyaf 29
                                 labelErrorNgaySinh.setText("Ngày tháng không hợp lệ");
                                test = false;
                                }
                            }
                        }
                    }
                    
                    try {
                         p.setDateOfBirth(new SimpleDateFormat("dd/MM/yyyy").parse(jTextFieldNgaySinh.getText())); // thiết lập ngày sinh
                    } catch (Exception e) {
                         labelErrorNgaySinh.setText("Ngày tháng phải nhập theo định dạng dd/MM/yyyy");
                    }
                     
                } else { // else if (jTextFieldNgaySinh.getText().matches(patternDate))
                   labelErrorNgaySinh.setText("Ngày tháng phải nhập theo định dạng dd/MM/yyyy");
                   test = false;
                }
             String patternPhone = "0[0-9]{9}"; // định dạng của số điện thoại
            if (jTextFieldSDT.getText().matches(patternPhone)) { // kiểm tra định dạng
                p.setPhoneNumer(jTextFieldSDT.getText());
            }
            else{
                labelErrorSDT.setText("Số điện thoại không hợp lệ");
                 test = false;
            }
             String patternEmail = "\\w+@\\w+.\\w+"; // định dạng email ___@___.___
            if (jTextFieldEmail.getText().matches(patternEmail)) {
                p.setEmail(jTextFieldEmail.getText());
            }
            else{
                 labelErrorEmail.setText("Email không hợp lệ");
                 test = false;
            }
            if(jRadioButtonNam.isSelected())
            {
                p.setSex("Nam");
            }
            else p.setSex("Nữ");
            if(jRadioButtonMeMangThai.isSelected())
            {
                p.setKindOfPatient("Mẹ mang thai");
            }
            else p.setKindOfPatient("Trẻ em");
            r.setID(Integer.parseInt(jTextFieldIDNt.getText()));
            r.setIDPatient(Integer.parseInt(jTextFieldID.getText()));
           if(jTextFieldHoTenNt.getText().equals("")){ // kiểm tra mục họ tên người thân cồn trống hay không
                labelErrorHotenNt.setText("Chưa nhập họ tên người thân");
                test = false;
            }
            else{
                r.setName(jTextFieldHoTenNt.getText());
            }
            if (jTextFieldSDTNt.getText().matches(patternPhone)) { // kiểm tra số điện thoại người thân có đúng định dạng
                r.setPhoneNumber(jTextFieldSDTNt.getText());
            }
            else{
                labelErrorSDTNt.setText("Số điện thoại không hợp lệ");
                 test = false;
            }
           
            r.setAddress(jTextFieldDiaChiNt.getText());
            if (jTextFieldQuanHe.getText().length()>10) {
                labelErrorQuanHe.setText("Quan hệ không hợp lê, do vượt quá kí tự");
                 test = false;
            }
            else{
                 r.setRelation(jTextFieldQuanHe.getText());
                
            }
           
            if (test) {
                if (new ClinicDAO().UpdatePatient(p) && new ClinicDAO().UpdateRelative(r)) {
                JOptionPane.showMessageDialog(rootPane, "Sửa thành công!");
            }
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void btnQuayLaiClick(){
        new FrameQuanLyBenhNhan().setVisible(true);
        this.dispose();
    }
    
    public void   btnLamMoiClick(){
        jTextFieldHoTen.setText("");
        jTextFieldNgaySinh.setText("");
        jTextFieldDiaChi.setText("");
        jTextFieldSDT.setText("");
        jTextFieldEmail.setText("");
        jRadioButtonNam.setSelected(false);
        jRadioButtonNu.setSelected(false);
        jRadioButtonMeMangThai.setSelected(false);
        jRadioButtonTre.setSelected(false);
        jTextFieldHoTenNt.setText("");
        jTextFieldDiaChiNt.setText("");
        jTextFieldSDTNt.setText("");
        jTextFieldQuanHe.setText("");
        
    }
}
