/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author Admin
 */
public class FrameXemThongTin extends javax.swing.JFrame {

    /**
     * Creates new form FrameXemThongTin
     */
    public FrameXemThongTin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonTTThaiKi = new javax.swing.JButton();
        jButtonCSDD = new javax.swing.JButton();
        jButtonLSTC = new javax.swing.JButton();
        jButtonNguoiThan = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButtonXemThongTinPhongKham = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Xem Thông Tin");
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setResizable(false);
        getContentPane().setLayout(null);

        jButtonTTThaiKi.setBackground(new java.awt.Color(0, 153, 102));
        jButtonTTThaiKi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonTTThaiKi.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTTThaiKi.setText("XEM THÔNG TIN THAI KỲ");
        jButtonTTThaiKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTTThaiKiActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTTThaiKi);
        jButtonTTThaiKi.setBounds(270, 100, 400, 37);

        jButtonCSDD.setBackground(new java.awt.Color(0, 153, 102));
        jButtonCSDD.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonCSDD.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCSDD.setText("XEM CHỈ SỐ DINH DƯỠNG");
        jButtonCSDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCSDDActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCSDD);
        jButtonCSDD.setBounds(270, 210, 400, 34);

        jButtonLSTC.setBackground(new java.awt.Color(0, 153, 102));
        jButtonLSTC.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonLSTC.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLSTC.setText("XEM LỊCH SỬ TIÊM CHỦNG");
        jButtonLSTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLSTCActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLSTC);
        jButtonLSTC.setBounds(270, 320, 400, 33);

        jButtonNguoiThan.setBackground(new java.awt.Color(0, 153, 102));
        jButtonNguoiThan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonNguoiThan.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNguoiThan.setText("XEM THÔNG TIN NGƯỜI THÂN");
        jButtonNguoiThan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNguoiThanActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNguoiThan);
        jButtonNguoiThan.setBounds(270, 430, 400, 39);

        jButtonExit.setBackground(new java.awt.Color(0, 153, 102));
        jButtonExit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExit.setText("QUAY LẠI");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit);
        jButtonExit.setBounds(270, 640, 400, 31);

        jButtonXemThongTinPhongKham.setBackground(new java.awt.Color(0, 153, 102));
        jButtonXemThongTinPhongKham.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonXemThongTinPhongKham.setForeground(new java.awt.Color(255, 255, 255));
        jButtonXemThongTinPhongKham.setText("XEM THÔNG TIN PHÒNG KHÁM");
        jButtonXemThongTinPhongKham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXemThongTinPhongKhamActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonXemThongTinPhongKham);
        jButtonXemThongTinPhongKham.setBounds(270, 530, 400, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/48360123_1946174842344109_3833490493317054464_n.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTTThaiKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTTThaiKiActionPerformed

        new FrameXemThongTinThaiKi().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTTThaiKiActionPerformed

    private void jButtonLSTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLSTCActionPerformed
    new FrameLichSuTiemChung().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLSTCActionPerformed

    private void jButtonCSDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCSDDActionPerformed
     new FrameXemChiSoDinhDuong().setVisible(true);
        this.dispose(); 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCSDDActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        new FrameTrangChu().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonNguoiThanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNguoiThanActionPerformed
        new FrameXemThongTinNguoiThan().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNguoiThanActionPerformed

    private void jButtonXemThongTinPhongKhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXemThongTinPhongKhamActionPerformed
        new FrameXemThongTinPhongKham().setVisible(true);
    this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonXemThongTinPhongKhamActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrameXemThongTin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrameXemThongTin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrameXemThongTin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrameXemThongTin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrameXemThongTin().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCSDD;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonLSTC;
    private javax.swing.JButton jButtonNguoiThan;
    private javax.swing.JButton jButtonTTThaiKi;
    private javax.swing.JButton jButtonXemThongTinPhongKham;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
