/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import connection.ClinicDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.HistoryOfVaccination;
import model.Patient;
import model.ThaiKi;

/**
 *
 * @author Admin
 */
public class FrameXemThongTinThaiKi extends javax.swing.JFrame {

    /**
     * Creates new form FrameXemThongTinThaiKy
     */
    private DefaultTableModel tblModel;
    public FrameXemThongTinThaiKi() {
        initComponents();
        setLocationRelativeTo(null);
        ArrayList<Patient> listPatient = new ClinicDAO().getAllPatient();
        ArrayList<ThaiKi> listThaiKi = new ClinicDAO().getAllThaiKi();
        setTableData(listPatient, listThaiKi);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableThaiKi = new javax.swing.JTable();
        jButtonTaoSuKien = new javax.swing.JButton();
        jButtonQuayLai = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonEdit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSearch = new javax.swing.JTextField();
        jbuttonSearch = new javax.swing.JButton();
        jButtonShowAll = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thai kì");
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setResizable(false);
        getContentPane().setLayout(null);

        jTableThaiKi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên", "Thời gian mang thai", "Cân nặng", "Ngày khám gần nhất", "Ngày tái khám"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableThaiKi);
        if (jTableThaiKi.getColumnModel().getColumnCount() > 0) {
            jTableThaiKi.getColumnModel().getColumn(0).setResizable(false);
            jTableThaiKi.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTableThaiKi.getColumnModel().getColumn(1).setResizable(false);
            jTableThaiKi.getColumnModel().getColumn(2).setResizable(false);
            jTableThaiKi.getColumnModel().getColumn(3).setResizable(false);
            jTableThaiKi.getColumnModel().getColumn(4).setResizable(false);
            jTableThaiKi.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 110, 1000, 550);

        jButtonTaoSuKien.setBackground(new java.awt.Color(0, 153, 102));
        jButtonTaoSuKien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonTaoSuKien.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTaoSuKien.setText("TẠO SỰ KIỆN");
        jButtonTaoSuKien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTaoSuKienActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTaoSuKien);
        jButtonTaoSuKien.setBounds(610, 690, 150, 40);

        jButtonQuayLai.setBackground(new java.awt.Color(0, 153, 102));
        jButtonQuayLai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonQuayLai.setForeground(new java.awt.Color(255, 255, 255));
        jButtonQuayLai.setText("QUAY LẠI");
        jButtonQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuayLaiActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonQuayLai);
        jButtonQuayLai.setBounds(120, 690, 140, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("THAI KÌ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(400, 20, 160, 29);

        jButtonEdit.setBackground(new java.awt.Color(0, 153, 102));
        jButtonEdit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonEdit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEdit.setText("SỬA THÔNG TIN THAI KÌ");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEdit);
        jButtonEdit.setBounds(320, 690, 239, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nhập họ tên bệnh nhân: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 70, 150, 20);
        getContentPane().add(jTextFieldSearch);
        jTextFieldSearch.setBounds(300, 60, 360, 30);

        jbuttonSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbuttonSearch.setText("TÌM KIẾM");
        jbuttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonSearchActionPerformed(evt);
            }
        });
        getContentPane().add(jbuttonSearch);
        jbuttonSearch.setBounds(700, 60, 90, 30);

        jButtonShowAll.setBackground(new java.awt.Color(0, 153, 102));
        jButtonShowAll.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonShowAll.setForeground(new java.awt.Color(255, 255, 255));
        jButtonShowAll.setText("HIỆN TẤT CẢ ");
        jButtonShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowAllActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonShowAll);
        jButtonShowAll.setBounds(810, 690, 150, 39);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/48360123_1946174842344109_3833490493317054464_n.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1000, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuayLaiActionPerformed
        new FrameXemThongTin().setVisible(true);
    this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonQuayLaiActionPerformed

    private void jButtonTaoSuKienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTaoSuKienActionPerformed
        new FrameTaoSuKien().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTaoSuKienActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        int row = jTableThaiKi.getSelectedRow();
        if(row==-1){
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn bệnh nhân trước"
                    + "", "Lỗi: ", JOptionPane.ERROR_MESSAGE);   
        }
        else{
        int ThaiKiID = Integer.valueOf(String.valueOf(jTableThaiKi.getValueAt(row, 0)));
         ArrayList<ThaiKi> thaiKis = new ClinicDAO().getAllThaiKi();
         
                
        int idEdit = thaiKis.get(row).getIDPatient();
        new FrameSuaTTThaiKi(idEdit).setVisible(true);
        this.dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jbuttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonSearchActionPerformed
        ArrayList<Patient> list = new ArrayList<>();
        String name  = jTextFieldSearch.getText().trim();
        list = new ClinicDAO().getPatientByName(name);
        ArrayList<ThaiKi> listThaiKi = new ArrayList<>();
        ArrayList<Patient> listMom = new ArrayList<>();
        for (Patient patient : list) {
            if (patient.getKindOfPatient().equals("Mẹ mang thai")) {
                listMom.add(patient);
            }
        }
        for (int i = 0; i < listMom.size(); i++) {
            listThaiKi.add(new ClinicDAO().getThaiKiByID(listMom.get(i).getID()));
        }
        if (listMom.size()<1) {
            JOptionPane.showMessageDialog(rootPane, "Không có bệnh nhân thỏa mãn!");
        }
        else{
            tblModel = (DefaultTableModel) jTableThaiKi.getModel();
            tblModel.setRowCount(0);
            for(int i = 0;i< listMom.size();  i++) {
                tblModel.addRow(new Object[]{listMom.get(i).getID(), listMom.get(i).getName(),
                    listThaiKi.get(i).getThoiGianMangThai(),
                    listThaiKi.get(i).getWeight(), listThaiKi.get(i).getNearestExaminationDate(),
                    listThaiKi.get(i).getReExaminationDate()

                });
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jbuttonSearchActionPerformed

    private void jButtonShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowAllActionPerformed
        tblModel.setRowCount(0);
        setTableData(new ClinicDAO().getAllPatient(), new ClinicDAO().getAllThaiKi());
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonShowAllActionPerformed
private void setTableData(ArrayList<Patient> listPatient, ArrayList<ThaiKi> listThaiKi){
    ArrayList<Patient> listPatientByThaiKi = new ArrayList<>();
        for (int i = 0; i < listThaiKi.size(); i++) {
            for (int j = 0; j < listPatient.size(); j++) {
                if(listPatient.get(j).getID()==listThaiKi.get(i).getIDPatient()){
                    listPatientByThaiKi.add(listPatient.get(j));
                }
                
            }
        }
        
        tblModel = (DefaultTableModel) jTableThaiKi.getModel();
        for(int i = 0;i< listThaiKi.size();  i++) {
                    tblModel.addRow(new Object[]{listThaiKi.get(i).getIDPatient(), listPatientByThaiKi.get(i).getName(), listThaiKi.get(i).getThoiGianMangThai(),
                        listThaiKi.get(i).getWeight(), listThaiKi.get(i).getNearestExaminationDate(),
                        listThaiKi.get(i).getReExaminationDate()

                    });
                }
}
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrameXemThongTinThaiKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrameXemThongTinThaiKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrameXemThongTinThaiKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrameXemThongTinThaiKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrameXemThongTinThaiKi().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonQuayLai;
    private javax.swing.JButton jButtonShowAll;
    private javax.swing.JButton jButtonTaoSuKien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableThaiKi;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JButton jbuttonSearch;
    // End of variables declaration//GEN-END:variables
}

