/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import connection.ClinicDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.ChiSoDinhDuong;
import model.HistoryOfVaccination;
import model.ThaiKi;

/**
 *
 * @author Admin
 */
public class FrameThemTTChiTietCuaTre extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form FrameThongTinTre
     */

            
    public FrameThemTTChiTietCuaTre(int id) {
        initComponents();
        setLocationRelativeTo(null);
        jTextFieldIDBenhNhanCSDD.setText(String.valueOf(id));
        jButtonExit.addActionListener(this);
        jButtonAdd.addActionListener(this);
        jButtonReset.addActionListener(this);
        jTextFieldIDBenhNhanCSDD.setText(String.valueOf(id));
        labelErrorChieuCaoMax.setText("");
        labelErrorCanNangMin.setText("");
        labelErrorCanNangMax.setText("");
        labelErrorChieuCaoMin.setText("");
        labelErrorCanNang.setText("");
        labelErrorChieuCao.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldIDBenhNhanCSDD = new javax.swing.JTextField();
        jTextFieldChieuCaoMax = new javax.swing.JTextField();
        JTextFieldChieuCaoMin = new javax.swing.JTextField();
        jTextFieldCanNangMax = new javax.swing.JTextField();
        jTextFieldCanNangMin = new javax.swing.JTextField();
        jButtonReset = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldChieuCao = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldCanNang = new javax.swing.JTextField();
        labelErrorChieuCaoMax = new javax.swing.JLabel();
        labelErrorChieuCaoMin = new javax.swing.JLabel();
        labelErrorCanNangMax = new javax.swing.JLabel();
        labelErrorCanNangMin = new javax.swing.JLabel();
        labelErrorChieuCao = new javax.swing.JLabel();
        labelErrorCanNang = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("CHỈ SỐ DINH DƯỠNG");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(380, 30, 280, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("ID Bệnh nhân");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 100, 100, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Chiều cao tối đa");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 180, 110, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Chiều cao tối thiểu");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 270, 120, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Cân nặng tối đa");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 370, 110, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Cân nặng tối thiểu");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(150, 460, 120, 17);

        jTextFieldIDBenhNhanCSDD.setEnabled(false);
        getContentPane().add(jTextFieldIDBenhNhanCSDD);
        jTextFieldIDBenhNhanCSDD.setBounds(320, 90, 440, 30);
        getContentPane().add(jTextFieldChieuCaoMax);
        jTextFieldChieuCaoMax.setBounds(320, 180, 440, 30);
        getContentPane().add(JTextFieldChieuCaoMin);
        JTextFieldChieuCaoMin.setBounds(320, 260, 440, 30);
        getContentPane().add(jTextFieldCanNangMax);
        jTextFieldCanNangMax.setBounds(320, 360, 440, 30);
        getContentPane().add(jTextFieldCanNangMin);
        jTextFieldCanNangMin.setBounds(320, 450, 440, 30);

        jButtonReset.setBackground(new java.awt.Color(0, 153, 102));
        jButtonReset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonReset.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReset.setText("Làm mới");
        getContentPane().add(jButtonReset);
        jButtonReset.setBounds(730, 710, 130, 40);

        jButtonExit.setBackground(new java.awt.Color(0, 153, 102));
        jButtonExit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExit.setText("Quay Lại");
        getContentPane().add(jButtonExit);
        jButtonExit.setBounds(250, 710, 130, 40);

        jButtonAdd.setBackground(new java.awt.Color(0, 153, 102));
        jButtonAdd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdd.setText("Thêm");
        getContentPane().add(jButtonAdd);
        jButtonAdd.setBounds(490, 710, 130, 40);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Chiều cao");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(180, 550, 80, 17);
        getContentPane().add(jTextFieldChieuCao);
        jTextFieldChieuCao.setBounds(320, 540, 440, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Cân  nặng");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(200, 630, 80, 17);

        jTextFieldCanNang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCanNangActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCanNang);
        jTextFieldCanNang.setBounds(320, 620, 440, 30);

        labelErrorChieuCaoMax.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorChieuCaoMax.setText("jLabel12");
        getContentPane().add(labelErrorChieuCaoMax);
        labelErrorChieuCaoMax.setBounds(320, 220, 160, 14);

        labelErrorChieuCaoMin.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorChieuCaoMin.setText("jLabel12");
        getContentPane().add(labelErrorChieuCaoMin);
        labelErrorChieuCaoMin.setBounds(320, 300, 160, 14);

        labelErrorCanNangMax.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorCanNangMax.setText("jLabel12");
        getContentPane().add(labelErrorCanNangMax);
        labelErrorCanNangMax.setBounds(320, 400, 160, 14);

        labelErrorCanNangMin.setForeground(new java.awt.Color(255, 51, 51));
        labelErrorCanNangMin.setText("jLabel12");
        getContentPane().add(labelErrorCanNangMin);
        labelErrorCanNangMin.setBounds(320, 490, 160, 14);

        labelErrorChieuCao.setForeground(new java.awt.Color(255, 0, 51));
        labelErrorChieuCao.setText("jLabel12");
        getContentPane().add(labelErrorChieuCao);
        labelErrorChieuCao.setBounds(320, 580, 160, 14);

        labelErrorCanNang.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorCanNang.setText("jLabel12");
        getContentPane().add(labelErrorCanNang);
        labelErrorCanNang.setBounds(320, 660, 160, 14);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/48360123_1946174842344109_3833490493317054464_n.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1000, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCanNangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCanNangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCanNangActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrameThemTTChiTietCuaTre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrameThemTTChiTietCuaTre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrameThemTTChiTietCuaTre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrameThemTTChiTietCuaTre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrameThemTTChiTietCuaTre().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextFieldChieuCaoMin;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextFieldCanNang;
    private javax.swing.JTextField jTextFieldCanNangMax;
    private javax.swing.JTextField jTextFieldCanNangMin;
    private javax.swing.JTextField jTextFieldChieuCao;
    private javax.swing.JTextField jTextFieldChieuCaoMax;
    private javax.swing.JTextField jTextFieldIDBenhNhanCSDD;
    private javax.swing.JLabel labelErrorCanNang;
    private javax.swing.JLabel labelErrorCanNangMax;
    private javax.swing.JLabel labelErrorCanNangMin;
    private javax.swing.JLabel labelErrorChieuCao;
    private javax.swing.JLabel labelErrorChieuCaoMax;
    private javax.swing.JLabel labelErrorChieuCaoMin;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource().equals(jButtonAdd)){
            btnAddClick();
        }
        else if(e.getSource().equals(jButtonExit)){
            btnQuayLaiClick();
        }
        
        else btnLamMoiClick();
    }
    public void btnAddClick(){
        ChiSoDinhDuong csdd = new ChiSoDinhDuong();
        labelErrorChieuCaoMax.setText("");
        labelErrorCanNangMin.setText("");
        labelErrorCanNangMax.setText("");
        labelErrorChieuCaoMin.setText("");
        labelErrorCanNang.setText("");
        labelErrorChieuCao.setText("");
        boolean test = true;
            try { // try1
                try { // sửa chiều cao
                float chieuCao = Float.parseFloat(jTextFieldChieuCao.getText());
                if (chieuCao < 0) {
                    labelErrorChieuCao.setText("Chiều cao không hợp lệ");
                    test = false;
                } else {
                    csdd.setHeight(chieuCao);
                }
            } catch (NumberFormatException e) {
                labelErrorChieuCao.setText("Chiều cao phải là một số");
                test = false;
            }
                try { // sửa cân nặng
                float canNang = Float.parseFloat(jTextFieldCanNang.getText());
                if (canNang < 0) {
                    labelErrorCanNang.setText("Cân nặng không hợp lệ");
                    test = false;
                } else {
                    csdd.setWeight(canNang);
                }
            } catch (NumberFormatException e) {
                labelErrorCanNang.setText("Cân nặng phải là một số");
                test = false;
            }
                try { // sửa chiều cao max
                float chieuCaoMax = Float.parseFloat(jTextFieldChieuCaoMax.getText());
                
                if (chieuCaoMax < 0) {
                    labelErrorChieuCaoMax.setText("Chiều cao không hợp lệ");
                    test = false;
                } else {
                    csdd.setMaxHeight(chieuCaoMax);
                }
                
            } catch (NumberFormatException e) {
                labelErrorChieuCaoMax.setText("Chiều cao phải là một số");
                test = false;
            }
                try { // sửa chiều cao min
                float chieuCaoMin = Float.parseFloat(JTextFieldChieuCaoMin.getText());
                if (chieuCaoMin < 0) {
                    labelErrorChieuCaoMin.setText("Chiều cao không hợp lệ");
                    test = false;
                } else {
                    csdd.setMinHeight(chieuCaoMin);
                }
            } catch (NumberFormatException e) {
                labelErrorChieuCaoMin.setText("Chiều cao phải là một số");
                test = false;
            }
                try { // sửa cân nặng max
                float canNangMax = Float.parseFloat(jTextFieldCanNangMax.getText());
                if (canNangMax < 0) {
                    labelErrorCanNangMax.setText("Cân nặng không hợp lệ");
                    test = false;
                } else {
                    csdd.setMaxWeight(canNangMax);
                }
            } catch (NumberFormatException e) {
                labelErrorCanNangMax.setText("Cân nặng phải là một số");
                test = false;
            }
                try { // sửa cân nặng min
                float canNangMin = Float.parseFloat(jTextFieldCanNangMin.getText());
                if (canNangMin < 0) {
                    labelErrorCanNangMin.setText("Cân nặng không hợp lệ");
                    test = false;
                } else {
                    csdd.setWeight(canNangMin);
                }
            } catch (NumberFormatException e) {
                labelErrorCanNangMin.setText("Cân nặng phải là một số");
                test = false;
            }
                try {
                    if(Float.parseFloat(jTextFieldChieuCaoMax.getText())<=Float.parseFloat(JTextFieldChieuCaoMin.getText())||
                            Float.parseFloat(jTextFieldCanNangMax.getText())<=Float.parseFloat(jTextFieldCanNangMin.getText())){
                        JOptionPane.showMessageDialog(rootPane, "Các chỉ số tối đa phải lớn hơn chỉ số tối thiểu");
                        test = false;
                    }
                } catch (Exception e) {
                }
             
                
                
            csdd.setIDPatient(Integer.parseInt(jTextFieldIDBenhNhanCSDD.getText()));
            if (test) {
                if (new ClinicDAO().addNew(csdd)) {
                    JOptionPane.showMessageDialog(rootPane, "Thêm thành công!");
                    new FrameThemBenhNhan().setVisible(true);
                    this.dispose();
                    }
                }
            
        } catch (Exception e) { // catch of try1
            e.printStackTrace();
        }
    }
    public void btnQuayLaiClick(){
        new FrameThemBenhNhan().setVisible(true);
        this.dispose();
    }
    public void btnLamMoiClick(){
        jTextFieldChieuCaoMax.setText("");
        JTextFieldChieuCaoMin.setText("");
        jTextFieldCanNangMax.setText("");
        jTextFieldCanNangMin.setText("");
        jTextFieldChieuCao.setText("");
        jTextFieldCanNang.setText("");
            
    }
}
