/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import connection.ClinicDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Patient;
import model.Relatives;
import model.ThaiKi;

/**
 *
 * @author Admin
 */
public class FrameXemThongTinNguoiThan extends javax.swing.JFrame {

    /**
     * Creates new form FrameXemThongTinNguoiThan
     */
    private DefaultTableModel tblModel;
    public FrameXemThongTinNguoiThan() {
        initComponents();
        setLocationRelativeTo(null);
        ArrayList<Patient> listPatient = new ClinicDAO().getAllPatient();
        ArrayList<Relatives> listRelative = new ClinicDAO().getAllRelatives();
        setTableData(listPatient, listRelative);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNguoiThan = new javax.swing.JTable();
        jButtonExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonShowAll = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSearch = new javax.swing.JTextField();
        jbuttonSearch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Người thân");
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setResizable(false);
        getContentPane().setLayout(null);

        jTableNguoiThan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên", "ID Bệnh nhân", "Tên Bệnh nhân", "SĐT", "Địa Chỉ", "Quan hệ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableNguoiThan);
        if (jTableNguoiThan.getColumnModel().getColumnCount() > 0) {
            jTableNguoiThan.getColumnModel().getColumn(0).setResizable(false);
            jTableNguoiThan.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTableNguoiThan.getColumnModel().getColumn(1).setResizable(false);
            jTableNguoiThan.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTableNguoiThan.getColumnModel().getColumn(2).setResizable(false);
            jTableNguoiThan.getColumnModel().getColumn(3).setResizable(false);
            jTableNguoiThan.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTableNguoiThan.getColumnModel().getColumn(4).setResizable(false);
            jTableNguoiThan.getColumnModel().getColumn(5).setResizable(false);
            jTableNguoiThan.getColumnModel().getColumn(5).setPreferredWidth(100);
            jTableNguoiThan.getColumnModel().getColumn(6).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 140, 1000, 520);

        jButtonExit.setBackground(new java.awt.Color(0, 153, 102));
        jButtonExit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExit.setText("QUAY LẠI");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit);
        jButtonExit.setBounds(550, 700, 160, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("THÔNG TIN NGƯỜI THÂN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 30, 330, 29);

        jButtonShowAll.setBackground(new java.awt.Color(0, 153, 102));
        jButtonShowAll.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonShowAll.setForeground(new java.awt.Color(255, 255, 255));
        jButtonShowAll.setText("HIỆN TẤT CẢ ");
        jButtonShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowAllActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonShowAll);
        jButtonShowAll.setBounds(790, 700, 150, 39);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nhập họ tên bệnh nhân: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 90, 150, 20);
        getContentPane().add(jTextFieldSearch);
        jTextFieldSearch.setBounds(320, 80, 360, 30);

        jbuttonSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbuttonSearch.setText("TÌM KIẾM");
        jbuttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonSearchActionPerformed(evt);
            }
        });
        getContentPane().add(jbuttonSearch);
        jbuttonSearch.setBounds(720, 80, 90, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/48360123_1946174842344109_3833490493317054464_n.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1000, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        new FrameXemThongTin().setVisible(true);
    this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowAllActionPerformed
        tblModel.setRowCount(0);
        setTableData(new ClinicDAO().getAllPatient(), new ClinicDAO().getAllRelatives());
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonShowAllActionPerformed

    private void jbuttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonSearchActionPerformed
    ArrayList<Patient> list = new ArrayList<>();
        String name  = jTextFieldSearch.getText().trim();
        list = new ClinicDAO().getPatientByName(name);
        ArrayList<Relatives> listRelative = new ArrayList<>();
        for (int i = 0; i < list.size(); i++) {
            listRelative.add(new ClinicDAO().getRelativeByID(list.get(i).getID()));
        }
        if (list.size()<1) {
            JOptionPane.showMessageDialog(rootPane, "Không có bệnh nhân thỏa mãn!");
        }
        else{
            tblModel = (DefaultTableModel) jTableNguoiThan.getModel();
            tblModel.setRowCount(0);
        for(int i = 0;i< listRelative.size();  i++) {
                    tblModel.addRow(new Object[]{listRelative.get(i).getIDPatient(), listRelative.get(i).getName(),
                        listRelative.get(i).getIDPatient(),list.get(i).getName(),
                        listRelative.get(i).getPhoneNumber(),
                        listRelative.get(i).getAddress(),
                        listRelative.get(i).getRelation()

                    });
                }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jbuttonSearchActionPerformed
private void setTableData(ArrayList<Patient> listPatient, ArrayList<Relatives> listRelative){
    ArrayList<Patient> listPatientByRelative = new ArrayList<>();
        for (int i = 0; i < listRelative.size(); i++) {
            for (int j = 0; j < listPatient.size(); j++) {
                if(listPatient.get(j).getID()==listRelative.get(i).getIDPatient()){
                    listPatientByRelative.add(listPatient.get(j));
                }
                
            }
        }
        
        tblModel = (DefaultTableModel) jTableNguoiThan.getModel();
        for(int i = 0;i< listRelative.size();  i++) {
                    tblModel.addRow(new Object[]{listRelative.get(i).getIDPatient(), listRelative.get(i).getName(),
                        listRelative.get(i).getIDPatient(),listPatientByRelative.get(i).getName(),
                        listRelative.get(i).getPhoneNumber(),
                        listRelative.get(i).getAddress(),
                        listRelative.get(i).getRelation()

                    });
                }
}
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrameXemThongTinNguoiThan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrameXemThongTinNguoiThan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrameXemThongTinNguoiThan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrameXemThongTinNguoiThan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrameXemThongTinNguoiThan().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonShowAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNguoiThan;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JButton jbuttonSearch;
    // End of variables declaration//GEN-END:variables
}
