/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import connection.ClinicDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.ThaiKi;

/**
 *
 * @author Admin
 */
public class FrameThemTTChiTietCuaMe extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form FrameThaiKi
     */
    public FrameThemTTChiTietCuaMe(int id) {
        initComponents();
        setLocationRelativeTo(null);
        jTextFieldID.setText(String.valueOf(id));
        jButtonExit.addActionListener(this);
        jButtonAdd.addActionListener(this);
        jButtonReset.addActionListener(this);
        jTextFieldID.setText(String.valueOf(id));
        labelShowErrorTGMangThai.setText("");
        labelErrorNgayKhamGanNhat.setText("");
        labelErrorNgayTaiKham.setText("");
        labelErrorCanNang.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelThaiKi = new javax.swing.JLabel();
        jLabelIDBenhNhan = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabelNgayKhamGanNhat = new javax.swing.JLabel();
        jTextFieldTGMangThai = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNgayKhamGanNhat = new javax.swing.JTextField();
        jLabelNgayTaiKham = new javax.swing.JLabel();
        jTextFieldNgayTaiKham = new javax.swing.JTextField();
        jButtonExit = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCanNang = new javax.swing.JTextField();
        labelShowErrorTGMangThai = new javax.swing.JLabel();
        labelErrorNgayKhamGanNhat = new javax.swing.JLabel();
        labelErrorNgayTaiKham = new javax.swing.JLabel();
        labelErrorCanNang = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelThaiKi.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelThaiKi.setText("    THAI KÌ");
        getContentPane().add(jLabelThaiKi);
        jLabelThaiKi.setBounds(378, 11, 230, 34);

        jLabelIDBenhNhan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelIDBenhNhan.setText("ID Bệnh Nhân");
        getContentPane().add(jLabelIDBenhNhan);
        jLabelIDBenhNhan.setBounds(150, 100, 85, 17);

        jTextFieldID.setText("ID Bệnh nhân tự đông cập nhật");
        jTextFieldID.setEnabled(false);
        getContentPane().add(jTextFieldID);
        jTextFieldID.setBounds(350, 100, 400, 29);

        jLabelNgayKhamGanNhat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNgayKhamGanNhat.setText("Thời gian mang thai (tháng) ");
        getContentPane().add(jLabelNgayKhamGanNhat);
        jLabelNgayKhamGanNhat.setBounds(140, 220, 174, 17);
        getContentPane().add(jTextFieldTGMangThai);
        jTextFieldTGMangThai.setBounds(360, 220, 390, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Ngày khám gần nhất");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 340, 129, 17);
        getContentPane().add(jTextFieldNgayKhamGanNhat);
        jTextFieldNgayKhamGanNhat.setBounds(360, 330, 390, 30);

        jLabelNgayTaiKham.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNgayTaiKham.setText("Ngày tái khám");
        getContentPane().add(jLabelNgayTaiKham);
        jLabelNgayTaiKham.setBounds(170, 480, 88, 17);
        getContentPane().add(jTextFieldNgayTaiKham);
        jTextFieldNgayTaiKham.setBounds(360, 470, 390, 30);

        jButtonExit.setBackground(new java.awt.Color(0, 153, 102));
        jButtonExit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExit.setText("Quay lại");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit);
        jButtonExit.setBounds(260, 700, 140, 40);

        jButtonReset.setBackground(new java.awt.Color(0, 153, 102));
        jButtonReset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonReset.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReset.setText("Làm mới");
        getContentPane().add(jButtonReset);
        jButtonReset.setBounds(480, 700, 120, 40);

        jButtonAdd.setBackground(new java.awt.Color(0, 153, 102));
        jButtonAdd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdd.setText("Thêm");
        getContentPane().add(jButtonAdd);
        jButtonAdd.setBounds(680, 700, 110, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cân nặng");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 610, 59, 17);
        getContentPane().add(jTextFieldCanNang);
        jTextFieldCanNang.setBounds(360, 600, 390, 30);

        labelShowErrorTGMangThai.setForeground(new java.awt.Color(255, 51, 51));
        labelShowErrorTGMangThai.setText("jLabel3");
        getContentPane().add(labelShowErrorTGMangThai);
        labelShowErrorTGMangThai.setBounds(360, 260, 300, 14);

        labelErrorNgayKhamGanNhat.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorNgayKhamGanNhat.setText("jLabel3");
        getContentPane().add(labelErrorNgayKhamGanNhat);
        labelErrorNgayKhamGanNhat.setBounds(360, 370, 300, 14);

        labelErrorNgayTaiKham.setForeground(new java.awt.Color(255, 51, 51));
        labelErrorNgayTaiKham.setText("jLabel3");
        getContentPane().add(labelErrorNgayTaiKham);
        labelErrorNgayTaiKham.setBounds(360, 510, 300, 14);

        labelErrorCanNang.setForeground(new java.awt.Color(255, 51, 51));
        labelErrorCanNang.setText("jLabel3");
        getContentPane().add(labelErrorCanNang);
        labelErrorCanNang.setBounds(360, 640, 300, 14);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/48360123_1946174842344109_3833490493317054464_n.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1000, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExitActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelIDBenhNhan;
    private javax.swing.JLabel jLabelNgayKhamGanNhat;
    private javax.swing.JLabel jLabelNgayTaiKham;
    private javax.swing.JLabel jLabelThaiKi;
    private javax.swing.JTextField jTextFieldCanNang;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldNgayKhamGanNhat;
    private javax.swing.JTextField jTextFieldNgayTaiKham;
    private javax.swing.JTextField jTextFieldTGMangThai;
    private javax.swing.JLabel labelErrorCanNang;
    private javax.swing.JLabel labelErrorNgayKhamGanNhat;
    private javax.swing.JLabel labelErrorNgayTaiKham;
    private javax.swing.JLabel labelShowErrorTGMangThai;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource().equals(jButtonAdd)){
            btnAddClick();
        }
        else if(e.getSource().equals(jButtonExit)){
            btnQuayLaiClick();
        }
        
        else btnLamMoiClick();
    }
    public void btnAddClick(){
        ThaiKi tk = new ThaiKi();
        boolean test = true;
        labelShowErrorTGMangThai.setText("");
        labelErrorNgayKhamGanNhat.setText("");
        labelErrorNgayTaiKham.setText("");
        labelErrorCanNang.setText("");
        try{
            tk.setIDPatient(Integer.parseInt(jTextFieldID.getText()));
            try {
            int thoiGianMangThai = Integer.parseInt(jTextFieldTGMangThai.getText());
            if(thoiGianMangThai<0||thoiGianMangThai>10){
                labelShowErrorTGMangThai.setText("Thời gian mang thai không hợp lệ");
                test = false;
            }
            else tk.setThoiGianMangThai(thoiGianMangThai);
            } catch (NumberFormatException e) {
                labelShowErrorTGMangThai.setText("Thời gian mang thai không hợp lệ");
                test = false;
            }
            
            try {
                float canNhang = Float.parseFloat(jTextFieldCanNang.getText());
                if (canNhang < 0) {
                    labelErrorCanNang.setText("Cân nặng không hợp lệ");
                    test = false;
                } else {
                    tk.setWeight(Float.parseFloat(jTextFieldCanNang.getText()));
                }
            } catch (NumberFormatException e) {
                labelErrorCanNang.setText("Chiều cao, cân nặng phải là một số");
                test = false;
            }
            if (testDate(jTextFieldNgayKhamGanNhat.getText())) { // nếu ngày đúng định dạng
                tk.setNearestExaminationDate(new SimpleDateFormat("dd/MM/yyyy").parse(jTextFieldNgayKhamGanNhat.getText())); // thiết lập ngày sinh
                    
            }
            else{
                labelErrorNgayKhamGanNhat.setText("Ngày tháng phải nhập theo định dạng dd/MM/yyyy");
                test = false;
            }
            if (testDate(jTextFieldNgayTaiKham.getText())) { // nếu ngày đúng định dạng
                 tk.setReExaminationDate(new SimpleDateFormat("dd/MM/yyyy").parse(jTextFieldNgayTaiKham.getText()));
            }
            else{
                labelErrorNgayTaiKham.setText("Ngày tháng phải nhập theo định dạng dd/MM/yyyy");
                test = false;
            }
            if(testDate(jTextFieldNgayKhamGanNhat.getText())&&testDate(jTextFieldNgayTaiKham.getText())){ // nếu ngày khám gần nhất và ngày tái khám đã hợp lệ
            if(new SimpleDateFormat("dd/MM/yyyy").parse(jTextFieldNgayTaiKham.getText()) // thì so sánh 2 ngày với nhau
                    .before(new SimpleDateFormat("dd/MM/yyyy").parse(jTextFieldNgayKhamGanNhat.getText()))){
                test = false;
                JOptionPane.showMessageDialog(rootPane, "Ngày tái khám phải sau ngày khám gần nhất"
                    + "", "Lỗi: ", JOptionPane.ERROR_MESSAGE);    
            }}
            if (test) {
                if (new ClinicDAO().addNew(tk)) {
                    JOptionPane.showMessageDialog(rootPane, "Thêm thành công!");
                    new FrameThemBenhNhan().setVisible(true);
                    this.dispose();
            }
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void btnQuayLaiClick(){
        new FrameThemBenhNhan().setVisible(true);
        this.dispose();
    }
    public void btnLamMoiClick(){
        jTextFieldNgayKhamGanNhat.setText("");
        jTextFieldNgayTaiKham.setText("");
        jTextFieldTGMangThai.setText("");
        jTextFieldCanNang.setText("");
    }
    public boolean testDate(String str){
        String patternDate = "[0-9]{2}/[0-9]{2}/[0-9]{4}"; // định dạng cua ngày sinh dd/MM/yyyy
                if (str.matches(patternDate)) { // kiểm tra xem nhày sinh nhập vào có đúng định dạng không
                    String date = str.substring(0, 2); // lấy ngày
                    String month = str.substring(3, 5); // lấy tháng
                    String year = str.substring(6, 10); // lấy năm
                    int dateNumber = Integer.parseInt(date); // chuyển ngày sang kiểu Int
                    int monthNumber = Integer.parseInt(month);
                    int yearNumber = Integer.parseInt(year);
                    if(monthNumber<0||monthNumber>12||dateNumber<0||dateNumber>31){ // nếu tháng > 12 hoặc <0 hoặc ngày < 0 hoặc ngày > 31 thì ngày sinh không hợp lệ
                        labelErrorNgayKhamGanNhat.setText("Ngày tháng không hợp lệ");
                       return  false;
                    }
                    else{
                        if(monthNumber==4||monthNumber==6||monthNumber==9||monthNumber==11) // nếu là tháng có 30 ngày
                        {
                            if(dateNumber==31){ // ngày = 31 không hợp lệ
                                labelErrorNgayKhamGanNhat.setText("Ngày tháng không hợp lệ");
                              return false;
                            }
                        }
                        if(monthNumber==2){ // nếu là tháng 2
                            if (!((yearNumber % 4 == 0 && yearNumber % 100 != 0) || (yearNumber % 400 == 0))){ // nếu không phải năm nhuận
                                if(dateNumber>=29){ // nếu xuất hiện ngày 29/2 trong năm không phải năm nhuận
                                labelErrorNgayKhamGanNhat.setText("Ngày tháng không hợp lệ");
                               return false;
                                }
                            }
                            else{ // nếu là năm nhuận
                                if (dateNumber>29) { // tháng 2 có thể có ngày 29
                                labelErrorNgayKhamGanNhat.setText("Ngày tháng không hợp lệ");
                               return false;
                                }
                            }
                        }
                    }
                     
                } else { // else if (jTextFieldNgaySinh.getText().matches(patternDate))
                   labelErrorNgayKhamGanNhat.setText("Ngày tháng phải nhập theo định dạng dd/MM/yyyy");
                   return false;
                }
                return true;
    }
}
