/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class FrameTrangChu extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form GDTrangChu
     */
    public FrameTrangChu() {
        initComponents();
        btnExit.addActionListener(this);
        btnQuanLiBenhNhan.addActionListener(this);
        btnXemThongTinBenhNhan.addActionListener(this);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnQuanLiBenhNhan = new javax.swing.JButton();
        btnXemThongTinBenhNhan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TRANG CHỦ");
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setResizable(false);
        getContentPane().setLayout(null);

        btnQuanLiBenhNhan.setBackground(new java.awt.Color(0, 204, 102));
        btnQuanLiBenhNhan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnQuanLiBenhNhan.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLiBenhNhan.setText("QUẢN LÝ BỆNH NHÂN");
        btnQuanLiBenhNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLiBenhNhanActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuanLiBenhNhan);
        btnQuanLiBenhNhan.setBounds(270, 190, 400, 46);

        btnXemThongTinBenhNhan.setBackground(new java.awt.Color(0, 204, 102));
        btnXemThongTinBenhNhan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnXemThongTinBenhNhan.setForeground(new java.awt.Color(255, 255, 255));
        btnXemThongTinBenhNhan.setText("TRA CỨU THÔNG TIN");
        getContentPane().add(btnXemThongTinBenhNhan);
        btnXemThongTinBenhNhan.setBounds(270, 300, 400, 46);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("TRẠM Y TẾ KIM ĐỒNG");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 40, 450, 60);

        btnExit.setBackground(new java.awt.Color(0, 204, 102));
        btnExit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("THOÁT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(270, 410, 400, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/hinh-nen-powerpoint-giot-nuoc-dep_123455035.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnQuanLiBenhNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLiBenhNhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuanLiBenhNhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameTrangChu().setVisible(true);
            }
        });
    }
    @Override
      public void actionPerformed(ActionEvent e) {
        if(e.getSource().equals(btnQuanLiBenhNhan)){
            btnQLBNClick();
        }
        if(e.getSource().equals(btnXemThongTinBenhNhan)){
            btnXemttClick();
        }
        if(e.getSource().equals(btnExit)){
            btnThoatClick();
        }
        
    }
  
    public void btnQLBNClick() {
        new FrameQuanLyBenhNhan ().setVisible(true);
        this.dispose();

    }
    public void btnXemttClick() {
        new FrameXemThongTin().setVisible(true);
        this.dispose();
    }
     public void btnThoatClick() {
         int cofirm = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn Thoát không ?");
         if (cofirm == JOptionPane.YES_OPTION) {
             System.exit(0);
         }
         else {
            new FrameTrangChu().setVisible(true);
         }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnQuanLiBenhNhan;
    private javax.swing.JButton btnXemThongTinBenhNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
